services:
  page_metadata.helper:
    class:     Druidvav\PageMetadataBundle\Templating\Helper\PageMetadataHelper
    arguments: [ "@page_metadata", "%page_metadata.options%" ]
    calls:
      - [ setContainer, [ "@service_container" ] ]
    tags:
      - { name: templating.helper, alias: "page_metadata" }
  page_metadata.twig:
    class:     Druidvav\PageMetadataBundle\Twig\Extension\PageMetadataExtension
    arguments: [ "@page_metadata.helper" ]
    tags:
      - { name: twig.extension }
